//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetCampus.Ipc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotnetCampus.Ipc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 IPC unknown error 的本地化字符串。
        /// </summary>
        internal static string DIPC001 {
            get {
                return ResourceManager.GetString("DIPC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown error occured when generating IPC types. The error is: {0} 的本地化字符串。
        /// </summary>
        internal static string DIPC001_Message {
            get {
                return ResourceManager.GetString("DIPC001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contract type not specified 的本地化字符串。
        /// </summary>
        internal static string DIPC002 {
            get {
                return ResourceManager.GetString("DIPC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IpcPublic attribute must have a contract type as its first argument. 的本地化字符串。
        /// </summary>
        internal static string DIPC002_Message {
            get {
                return ResourceManager.GetString("DIPC002_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPC contract type must be an interface 的本地化字符串。
        /// </summary>
        internal static string DIPC003 {
            get {
                return ResourceManager.GetString("DIPC003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPC contract type must be an interface but {0} is not. 的本地化字符串。
        /// </summary>
        internal static string DIPC003_Message {
            get {
                return ResourceManager.GetString("DIPC003_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPC contract type dismatches with interface 的本地化字符串。
        /// </summary>
        internal static string DIPC004 {
            get {
                return ResourceManager.GetString("DIPC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} does not implement the contract type {1} that the IpcPublic marked. 的本地化字符串。
        /// </summary>
        internal static string DIPC004_Message {
            get {
                return ResourceManager.GetString("DIPC004_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPC Proxy cannot be generated 的本地化字符串。
        /// </summary>
        internal static string DIPC010 {
            get {
                return ResourceManager.GetString("DIPC010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no type in this assembly implements the IPC contract interface {0}, so you need to set one explicitly as the second type argument. 的本地化字符串。
        /// </summary>
        internal static string DIPC010_Message {
            get {
                return ResourceManager.GetString("DIPC010_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IPC proxy type does not match the IPC contract type 的本地化字符串。
        /// </summary>
        internal static string DIPC011 {
            get {
                return ResourceManager.GetString("DIPC011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IPC proxy type {0} does not match the IPC contract type {1}. 的本地化字符串。
        /// </summary>
        internal static string DIPC011_Message {
            get {
                return ResourceManager.GetString("DIPC011_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IPC joint type does not match the IPC contract type 的本地化字符串。
        /// </summary>
        internal static string DIPC012 {
            get {
                return ResourceManager.GetString("DIPC012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IPC joint type {0} does not match the IPC contract type {1}. 的本地化字符串。
        /// </summary>
        internal static string DIPC012_Message {
            get {
                return ResourceManager.GetString("DIPC012_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only method or property is supported 的本地化字符串。
        /// </summary>
        internal static string DIPC020 {
            get {
                return ResourceManager.GetString("DIPC020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown IPC member {0}. IPC object only supports methods and properties. 的本地化字符串。
        /// </summary>
        internal static string DIPC020_Message {
            get {
                return ResourceManager.GetString("DIPC020_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event is not supported for an IPC object 的本地化字符串。
        /// </summary>
        internal static string DIPC021 {
            get {
                return ResourceManager.GetString("DIPC021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event {0} is not supported for an IPC object. 的本地化字符串。
        /// </summary>
        internal static string DIPC021_Message {
            get {
                return ResourceManager.GetString("DIPC021_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set-only property is not supported 的本地化字符串。
        /// </summary>
        internal static string DIPC022 {
            get {
                return ResourceManager.GetString("DIPC022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown IPC property {0}. Only get or get-set property is supported. 的本地化字符串。
        /// </summary>
        internal static string DIPC022_Message {
            get {
                return ResourceManager.GetString("DIPC022_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IgnoresIpcException is recommended 的本地化字符串。
        /// </summary>
        internal static string DIPC101 {
            get {
                return ResourceManager.GetString("DIPC101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set IgnoresIpcException to true 的本地化字符串。
        /// </summary>
        internal static string DIPC101_Fix1 {
            get {
                return ResourceManager.GetString("DIPC101_Fix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set IgnoresIpcException to false 的本地化字符串。
        /// </summary>
        internal static string DIPC101_Fix2 {
            get {
                return ResourceManager.GetString("DIPC101_Fix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For better readability, IgnoresIpcException is recommended to set so that the developers know that there may have been some IPC exceptions here. 的本地化字符串。
        /// </summary>
        internal static string DIPC101_Message {
            get {
                return ResourceManager.GetString("DIPC101_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPC timeout can&apos;t be negative 的本地化字符串。
        /// </summary>
        internal static string DIPC102 {
            get {
                return ResourceManager.GetString("DIPC102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPC timeout can&apos;t be negative, but it is set to {0}ms. 的本地化字符串。
        /// </summary>
        internal static string DIPC102_Message {
            get {
                return ResourceManager.GetString("DIPC102_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The timeout is zero 的本地化字符串。
        /// </summary>
        internal static string DIPC103 {
            get {
                return ResourceManager.GetString("DIPC103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A timeout with zero milliseconds does nothing so there is no need to assign this property. 的本地化字符串。
        /// </summary>
        internal static string DIPC103_Message {
            get {
                return ResourceManager.GetString("DIPC103_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DefaultReturn is useless 的本地化字符串。
        /// </summary>
        internal static string DIPC120 {
            get {
                return ResourceManager.GetString("DIPC120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the DefaultReturn 的本地化字符串。
        /// </summary>
        internal static string DIPC120_Fix1 {
            get {
                return ResourceManager.GetString("DIPC120_Fix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set IgnoresIpcException to true 的本地化字符串。
        /// </summary>
        internal static string DIPC120_Fix2 {
            get {
                return ResourceManager.GetString("DIPC120_Fix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DefaultReturn only works with the situation in which IgnoresIpcException is set to true. 的本地化字符串。
        /// </summary>
        internal static string DIPC120_Message {
            get {
                return ResourceManager.GetString("DIPC120_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty IPC member attribute is not needed 的本地化字符串。
        /// </summary>
        internal static string DIPC121 {
            get {
                return ResourceManager.GetString("DIPC121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the {0} 的本地化字符串。
        /// </summary>
        internal static string DIPC121_Fix {
            get {
                return ResourceManager.GetString("DIPC121_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty {0} does nothing, so there is no need to add it. 的本地化字符串。
        /// </summary>
        internal static string DIPC121_Message {
            get {
                return ResourceManager.GetString("DIPC121_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitsVoid is recommended 的本地化字符串。
        /// </summary>
        internal static string DIPC122 {
            get {
                return ResourceManager.GetString("DIPC122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commonly, developers can hardly determin whether a waiting is happened during an IPC call if a method returns void. So it&apos;s recommended to assign WaitsVoid to the value you want instead of keeping it as false by default. 的本地化字符串。
        /// </summary>
        internal static string DIPC122_Message {
            get {
                return ResourceManager.GetString("DIPC122_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsReadonly is unnecessary 的本地化字符串。
        /// </summary>
        internal static string DIPC123 {
            get {
                return ResourceManager.GetString("DIPC123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsReadonly is set to false by default, so there is no need to assign it to false manully. 的本地化字符串。
        /// </summary>
        internal static string DIPC123_Message {
            get {
                return ResourceManager.GetString("DIPC123_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DefaultReturn type does not match the property type 的本地化字符串。
        /// </summary>
        internal static string DIPC124 {
            get {
                return ResourceManager.GetString("DIPC124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IPC DefaultReturn type {0} does not match the property type {1}. 的本地化字符串。
        /// </summary>
        internal static string DIPC124_Message {
            get {
                return ResourceManager.GetString("DIPC124_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DefaultReturn type does not match the method return type 的本地化字符串。
        /// </summary>
        internal static string DIPC125 {
            get {
                return ResourceManager.GetString("DIPC125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IPC DefaultReturn type {0} does not match the method return type {1}. 的本地化字符串。
        /// </summary>
        internal static string DIPC125_Message {
            get {
                return ResourceManager.GetString("DIPC125_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DefaultReturn value for a void method is useless 的本地化字符串。
        /// </summary>
        internal static string DIPC126 {
            get {
                return ResourceManager.GetString("DIPC126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DefaultReturn value for a void method {0} is useless. 的本地化字符串。
        /// </summary>
        internal static string DIPC126_Message {
            get {
                return ResourceManager.GetString("DIPC126_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string is treated as a code snippet 的本地化字符串。
        /// </summary>
        internal static string DIPC127 {
            get {
                return ResourceManager.GetString("DIPC127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string {0} is treated as a code snippet and will be set to an object type. If you want to set the original string to it, use @&quot;&quot;&quot;{0}&quot;&quot;&quot; instead. 的本地化字符串。
        /// </summary>
        internal static string DIPC127_Message {
            get {
                return ResourceManager.GetString("DIPC127_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string is treated as a code snippet 的本地化字符串。
        /// </summary>
        internal static string DIPC128 {
            get {
                return ResourceManager.GetString("DIPC128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string {0} is treated as a code snippet and will be set to a {1} type. 的本地化字符串。
        /// </summary>
        internal static string DIPC128_Message {
            get {
                return ResourceManager.GetString("DIPC128_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string is treated as a code snippet but cannot be compiled 的本地化字符串。
        /// </summary>
        internal static string DIPC129 {
            get {
                return ResourceManager.GetString("DIPC129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string {0} is treated as a code snippet but cannot be compiled. 的本地化字符串。
        /// </summary>
        internal static string DIPC129_Message {
            get {
                return ResourceManager.GetString("DIPC129_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The WaitsVoid is useless 的本地化字符串。
        /// </summary>
        internal static string DIPC130 {
            get {
                return ResourceManager.GetString("DIPC130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This method has a return value so WaitsVoid does not work for it. 的本地化字符串。
        /// </summary>
        internal static string DIPC130_Message {
            get {
                return ResourceManager.GetString("DIPC130_Message", resourceCulture);
            }
        }
    }
}
