//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetCampus.Ipc.Analyzers.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotnetCampus.Ipc.Analyzers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 IPC unknown error 的本地化字符串。
        /// </summary>
        internal static string DIPC001 {
            get {
                return ResourceManager.GetString("DIPC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown error occured when generating IPC types. The error is: {0} 的本地化字符串。
        /// </summary>
        internal static string DIPC001_Message {
            get {
                return ResourceManager.GetString("DIPC001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contract type not specified 的本地化字符串。
        /// </summary>
        internal static string DIPC002 {
            get {
                return ResourceManager.GetString("DIPC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IpcPublic attribute must have a contract type as its first argument. 的本地化字符串。
        /// </summary>
        internal static string DIPC002_Message {
            get {
                return ResourceManager.GetString("DIPC002_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only method or property is supported 的本地化字符串。
        /// </summary>
        internal static string DIPC003 {
            get {
                return ResourceManager.GetString("DIPC003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown IPC member {0}. IPC object only supports methods and properties. 的本地化字符串。
        /// </summary>
        internal static string DIPC003_Message {
            get {
                return ResourceManager.GetString("DIPC003_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set-only property is not supported 的本地化字符串。
        /// </summary>
        internal static string DIPC004 {
            get {
                return ResourceManager.GetString("DIPC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown IPC property {0}. Only get or get-set property is supported. 的本地化字符串。
        /// </summary>
        internal static string DIPC004_Message {
            get {
                return ResourceManager.GetString("DIPC004_Message", resourceCulture);
            }
        }
    }
}
